INSERT INTO tasks (image, company, title, description, badgeType) VALUES
('https://via.placeholder.com/150', 'Company A', 'Task A', 'Task A Description', 'Normal'),
('https://via.placeholder.com/150', 'Company B', 'Task B', 'Task B Description', 'Gold'),
('https://via.placeholder.com/150', 'Company C', 'Task C', 'Task C Description', 'Silver'),
('https://via.placeholder.com/150', 'Company D', 'Task D', 'Task D Description', 'Bronze'),
('https://via.placeholder.com/150', 'Company E', 'Task E', 'Task E Description', 'Gold'),
('https://via.placeholder.com/150', 'Company F', 'Task F', 'Task F Description', 'Silver'),
('https://via.placeholder.com/150', 'Company G', 'Task G', 'Task G Description', 'Normal'),
('https://via.placeholder.com/150', 'Company H', 'Task H', 'Task H Description', 'Bronze'),
('https://via.placeholder.com/150', 'Company I', 'Task I', 'Task I Description', 'Gold'),
('https://via.placeholder.com/150', 'Company J', 'Task J', 'Task J Description', 'Silver');
